services:
  backend:
    build:
      context: .
      args:
        - NODE_ENV=test
    restart: always
    ports:
      - "3000:3000"
      - "8080:8080"
    env_file:
      - ./.env.test
    depends_on:
      - test-db
      - test-redis
    command: >
      sh -c "npm run deploy && npm run start:dev"

  test-db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: test-password
      POSTGRES_DB: test-DB

  test-redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"