services:
  backend:
    build:
      context: .
      args:
        - NODE_ENV=development
    volumes:
      - .:/usr/src/app:delegated
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    command: >
      sh -c "npx prisma migrate dev && npm run start:dev"
